# Generated by Django 6.0.2 on 2026-02-10 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('curso', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptoCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto_estandar', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_recibido', models.IntegerField()),
                ('saldo_disponible', models.IntegerField()),
                ('fecha_pago', models.DateField()),
                ('comprobante', models.CharField(blank=True, max_length=100)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='gestion.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='apoderado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pupilos', to='gestion.apoderado'),
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.IntegerField()),
                ('monto_pagado', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago Parcial'), ('PAGADO', 'Pagado completamente')], default='PENDIENTE', max_length=10)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='gestion.alumno')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.conceptocobro')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_asignado', models.IntegerField()),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('abono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='gestion.abono')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='gestion.cargo')),
            ],
        ),
    ]
