# Generated by Django 6.0.2 on 2026-03-05 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('numero_lista', models.IntegerField()),
                ('curso', models.CharField(choices=[('8B', '8° Básico')], default='8B', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptoCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto_estandar', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('destino', models.CharField(choices=[('VIAJE', 'Fondo Gira de Estudio (Ahorro)'), ('EXTERNO', 'Recaudación Externa (Centro Padres, Alianza, etc.)')], default='VIAJE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('REUNION', 'Reunión'), ('ACTIVIDAD', 'Actividad'), ('COBRO', 'Cobro / Rifa'), ('ACADEMICO', 'Académico')], default='ACTIVIDAD', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('fecha_transferencia', models.DateField()),
                ('comprobante', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('REVISION', 'En Revisión'), ('APROBADO', 'Aprobado (Saldo Disponible)'), ('RECHAZADO', 'Rechazado')], default='REVISION', max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='gestion.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='apoderados',
            field=models.ManyToManyField(related_name='pupilos', to='gestion.apoderado'),
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.IntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado completamente')], default='PENDIENTE', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='gestion.alumno')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.conceptocobro')),
            ],
            options={
                'ordering': ['estado', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CuentaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_ahorro', models.IntegerField(default=0)),
                ('saldo_disponible', models.IntegerField(default=0)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta', to='gestion.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso de Dinero (+)'), ('EGRESO', 'Pago de Deuda o Retiro (-)')], max_length=10)),
                ('monto', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='gestion.cuentaalumno')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('es_importante', models.BooleanField(default=False)),
                ('etiqueta', models.CharField(choices=[('GENERAL', 'General 📢'), ('FINANZAS', 'Finanzas 💰'), ('ACADEMICO', 'Académico 🎓'), ('URGENTE', 'Urgente 🚨'), ('SOCIAL', 'Social 🎉')], default='GENERAL', max_length=20)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe_cambiar_clave', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
