# Generated by Django 6.0.2 on 2026-02-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='curso',
            field=models.CharField(choices=[('8B', '8° Básico'), ('1M', '1° Medio')], max_length=10),
        ),
    ]
