# Generated by Django 6.0.2 on 2026-02-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_alumno_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptocobro',
            name='tipo',
            field=models.CharField(choices=[('MENSUALIDAD', 'Mensualidad (Cuota)'), ('EXTRA', 'Extra (Paseos, Rifas, etc.)')], default='MENSUALIDAD', max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='curso',
            field=models.CharField(choices=[('8B', '8° Básico'), ('1M', '1° Medio'), ('2M', '2° Medio'), ('3M', '3° Medio'), ('4M', '4° Medio')], max_length=10),
        ),
    ]
