# Generated by Django 6.0.2 on 2026-03-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_apoderado_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositoPlazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('alumnos_beneficiarios', models.ManyToManyField(blank=True, related_name='depositos', to='gestion.alumno')),
            ],
        ),
    ]
