# Generated by Django 6.0.2 on 2026-03-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_depositoplazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EgresoTesoreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_gasto', models.DateField()),
                ('comprobante', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_gasto', '-fecha_registro'],
            },
        ),
        migrations.AlterField(
            model_name='conceptocobro',
            name='destino',
            field=models.CharField(choices=[('CUENTA', 'Fondo del Curso (Cuotas, Salidas, Regalos)'), ('EXTERNO', 'Aportes Extra o Voluntarios (Rifas, Solidario, Otros)')], default='CUENTA', max_length=20),
        ),
    ]
