# Generated by Django 6.0.2 on 2026-02-16 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_conceptocobro_tipo_alter_alumno_curso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('es_importante', models.BooleanField(default=False)),
                ('etiqueta', models.CharField(choices=[('GENERAL', 'General 📢'), ('FINANZAS', 'Finanzas 💰'), ('ACADEMICO', 'Académico 🎓'), ('URGENTE', 'Urgente 🚨'), ('SOCIAL', 'Social 🎉')], default='GENERAL', max_length=20)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
