# Generated by Django 6.0.2 on 2026-03-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_egresotesoreria_alter_conceptocobro_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptocobro',
            name='estado_fondo',
            field=models.CharField(choices=[('RECAUDANDO', 'En Recaudación'), ('RENDIDO', 'Rendido / Transferido al Proveedor')], default='RECAUDANDO', max_length=20),
        ),
    ]
