# Generated by Django 6.0.2 on 2026-02-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('REUNION', 'Reunión'), ('ACTIVIDAD', 'Actividad'), ('COBRO', 'Cobro / Rifa'), ('ACADEMICO', 'Académico')], default='ACTIVIDAD', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
