# Generated by Django 6.0.2 on 2026-03-16 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_conceptocobro_estado_fondo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='noticias/archivos/'),
        ),
        migrations.CreateModel(
            name='ImagenGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='noticias/galeria/')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='gestion.noticia')),
            ],
        ),
    ]
