# Generated by Django 6.0.2 on 2026-03-03 00:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_alumno_curso_perfilusuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['estado', '-fecha_creacion']},
        ),
        migrations.RenameField(
            model_name='abono',
            old_name='fecha_pago',
            new_name='fecha_transferencia',
        ),
        migrations.RenameField(
            model_name='abono',
            old_name='monto_recibido',
            new_name='monto',
        ),
        migrations.RemoveField(
            model_name='abono',
            name='saldo_disponible',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='monto_pagado',
        ),
        migrations.RemoveField(
            model_name='conceptocobro',
            name='tipo',
        ),
        migrations.AddField(
            model_name='abono',
            name='estado',
            field=models.CharField(choices=[('REVISION', 'En Revisión'), ('APROBADO', 'Aprobado (Saldo Disponible)'), ('RECHAZADO', 'Rechazado')], default='REVISION', max_length=15),
        ),
        migrations.AddField(
            model_name='abono',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptocobro',
            name='destino',
            field=models.CharField(choices=[('VIAJE', 'Fondo Gira de Estudio (Ahorro)'), ('EXTERNO', 'Recaudación Externa (Centro Padres, Alianza, etc.)')], default='VIAJE', max_length=20),
        ),
        migrations.AlterField(
            model_name='abono',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado completamente')], default='PENDIENTE', max_length=10),
        ),
        migrations.CreateModel(
            name='CuentaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ahorro_historico', models.IntegerField(default=0)),
                ('fondo_viaje_actual', models.IntegerField(default=0)),
                ('saldo_disponible', models.IntegerField(default=0)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta', to='gestion.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso de Dinero (+)'), ('EGRESO', 'Pago de Deuda o Retiro (-)')], max_length=10)),
                ('monto', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='gestion.cuentaalumno')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.DeleteModel(
            name='AsignacionPago',
        ),
    ]
