# Generated by Django 6.0.2 on 2026-03-16 22:39

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_noticia_archivo_imagengaleria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='archivo',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='noticias/archivos/'),
        ),
    ]
