# Generated by Django 6.0.2 on 2026-03-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_cargo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='comprobante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
