# Generated by Django 6.0.2 on 2026-03-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_noticia_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='etiqueta',
            field=models.CharField(choices=[('GENERAL', 'General 📢'), ('ACADEMICO', 'Académico 📚'), ('REUNION', 'Reunión 👥'), ('URGENTE', 'Urgente 🚨'), ('SOCIAL', 'Social 🎉'), ('FINANZAS', 'Finanzas 💵'), ('COBRANZA', 'Cobranza 💰')], default='GENERAL', max_length=20),
        ),
    ]
